apiVersion: v1
kind: Service
metadata:
  name: backend-catalog-nodeport
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-catalog
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080   # PORT PARA ACCEDER DESDE EL HOST
