apiVersion: v1
kind: Service
metadata:
  name: backend-reviews-nodeport
  namespace: backends
spec:
  type: NodePort
  selector:
    app: backend-reviews
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30082
